language: php

sudo: false

cache:
  directories:
    - .autoconf
    - $HOME/.composer

branches:
  only:
    - master

addons:
  postgresql: "9.6"

services:
  - mysql
  - postgresql

matrix:
  include:
    - php: 7.1.20
      env: DATABASE="postgresql" ORO_PLATFORM="3.1.0-beta"

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - phpenv config-add travis.php.ini

install:
  - git clone -b ${ORO_PLATFORM} https://github.com/oroinc/platform-application.git /tmp/platform
  - composer config repositories.repo-test path ${PWD} --working-dir=/tmp/platform
  - composer require --no-update "okvpn/datadog-orocrm:*" --working-dir=/tmp/platform
  - travis_wait composer update --no-interaction --no-suggest --prefer-dist --working-dir=/tmp/platform
  - composer info --working-dir=/tmp/platform | grep okvpn
  - bash tests/run.sh install

before_script:
  - bash tests/run.sh before_script

script:
  - cd /tmp/platform; composer info | grep okvpn
