okvpn_datadog:
    handle_exceptions:
        skip_command:
            - 'oro:message-queue:consume'
    artifacts_path: '%artifacts_path%'

oro_message_queue:
    persistent_services:
        - 'okvpn_datadog.error_bag'

security:
    firewalls:
        datadog_api:
            pattern:   ^/datadog/artifact/(\w+)/jira$
            provider:   chain_provider
            anonymous:  true
